<?php
// OOXML generator for the SmartExam Pro handover pack. No external PHP package required.
$out = __DIR__ . '\\SmartExam_Pro_KT_Handover_Document.docx';
function x($s){ return htmlspecialchars($s, ENT_XML1 | ENT_QUOTES, 'UTF-8'); }
function r($s,$b=false,$color='202630',$size=21){ return '<w:r><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:color w:val="'.$color.'"/><w:sz w:val="'.$size.'"/>'.($b?'<w:b/>':'').'</w:rPr><w:t xml:space="preserve">'.x($s).'</w:t></w:r>'; }
function p($s='',$style='', $b=false,$color='202630',$size=21,$center=false,$page=false){ return '<w:p><w:pPr>'.($style?'<w:pStyle w:val="'.$style.'"/>':'').($center?'<w:jc w:val="center"/>':'').($page?'<w:rPr/> <w:pageBreakBefore/>':'').'</w:pPr>'.r($s,$b,$color,$size).'</w:p>'; }
function bullet($s){ return '<w:p><w:pPr><w:pStyle w:val="ListBullet"/></w:pPr>'.r($s,false,'202630',20).'</w:p>'; }
function tbl($headers,$rows){ $xml='<w:tbl><w:tblPr><w:tblW w:w="9360" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D9E1EA"/><w:left w:val="single" w:sz="4" w:color="D9E1EA"/><w:bottom w:val="single" w:sz="4" w:color="D9E1EA"/><w:right w:val="single" w:sz="4" w:color="D9E1EA"/><w:insideH w:val="single" w:sz="4" w:color="D9E1EA"/><w:insideV w:val="single" w:sz="4" w:color="D9E1EA"/></w:tblBorders><w:tblCellMar><w:top w:w="110" w:type="dxa"/><w:start w:w="120" w:type="dxa"/><w:bottom w:w="110" w:type="dxa"/><w:end w:w="120" w:type="dxa"/></w:tblCellMar></w:tblPr>';
 $row=function($cells,$head=false) { $z='<w:tr>'.($head?'<w:trPr><w:tblHeader/></w:trPr>':''); foreach($cells as $c){$z.='<w:tc><w:tcPr>'.($head?'<w:shd w:fill="10233F"/>':'').'</w:tcPr><w:p>'.r($c,$head,$head?'FFFFFF':'202630',$head?18:18).'</w:p></w:tc>'; } return $z.'</w:tr>';}; $xml.=$row($headers,true); foreach($rows as $rr)$xml.=$row($rr); return $xml.'</w:tbl><w:p/>'; }
$body='';
// Cover
$body .= '<w:p><w:pPr><w:spacing w:after="800"/></w:pPr></w:p>';
$body .= p('ENGINEERING HANDOVER','Kicker',true,'C89B3C',20).p('SmartExam Pro','Title',true,'10233F',56).p('Full Project Knowledge Transfer Document','Subtitle',false,'65758B',27).'<w:p><w:pPr><w:spacing w:after="450"/></w:pPr></w:p>';
$body .= tbl(['DOCUMENT','DETAILS'],[['Application','Online examination management platform'],['Architecture','PHP + MySQL monolith, served with XAMPP / Apache'],['Repository','C:\\xampp\\htdocs\\exam'],['Prepared','18 August 2026']]);
$body .= p('Purpose','Heading1',true,'C89B3C',25).p('This executive-style KT pack equips a new owner to run, support, troubleshoot and safely evolve SmartExam Pro. All findings are grounded in the repository reviewed on 18 August 2026.','Normal',false,'202630',22).'<w:p><w:r><w:br w:type="page"/></w:r></w:p>';
// Sections
$sections = [
['Executive briefing',[
['text','SmartExam Pro is a browser-based examination platform for assigning assessments, capturing answers and producing immediate scores. It is implemented as server-rendered PHP pages backed by MySQL and runs locally under XAMPP. The solution has no framework, migrations, dependency manifest or centralized authorization layer; stabilization should precede new feature work.'],
['table',['Area','What the system delivers','Primary owner'],[['Student experience','Registration, login, upcoming exams, passkey entry, timed MCQ attempt, score history and PDF output.','Application support'],['Admin experience','Exam and section creation, question drafting, candidate/passkey selection and score review.','Exam operations'],['Data & grading','MySQL persistence for users, exams, questions, passkeys, answers and scores.','Database owner'],['Runtime','Apache/PHP through XAMPP; MySQL database exam; Bootstrap and SweetAlert2 CDNs.','Infrastructure support']]],
['h2','Critical handover note'],['call','RELEASE READINESS','add_question.php calls save_questions.php, but that endpoint is absent from the repository root. Exam-question publishing will fail until the endpoint is restored or the client flow is changed.'],
['h2','Scope and assumptions'],['bullet','This document reflects source files available in C:\\xampp\\htdocs\\exam; no live database dump or deployed environment was inspected.'],['bullet','Database structures are inferred from queries and the schema utility. Validate types, keys and constraints on the target MySQL server.']]],
['Solution architecture',[
['text','The application is a classic PHP monolith: pages contain presentation, request handling and database access. config.php creates a global mysqli connection; PHP sessions retain user state; the browser uses fetch() for score submission and question publishing.'],
['table',['Layer','Implementation','Notes'],[['Presentation','Server-rendered HTML, Bootstrap 4/5 CDN, custom CSS, SweetAlert2','Mixed Bootstrap versions are used.'],['Application','Standalone PHP pages with inline SQL and JavaScript','No routing, service, repository or middleware abstraction.'],['Data','MySQL / mysqli','Local defaults: localhost, root, blank password, database exam.'],['Session','PHP native sessions','User: user_logged_in, registration_id, fullname; admin: admin_logged_in.'],['Reporting','Bundled FPDF','f_pdf.php generates results output.']]],
['h2','Runtime request path'],['table',['Step','Flow'],[['1','Browser requests a PHP page through Apache at http://localhost/exam/.'],['2','Page starts/reuses PHP session and includes config.php where needed.'],['3','Page executes mysqli queries directly against the exam database.'],['4','HTML is rendered; async fetch calls return JSON where required.'],['5','Responses redirect to dashboards or return data for alerts.']]]]],
['Repository map',[
['table',['Area','Key files','Responsibility'],[['Configuration','config.php','Creates MySQL connection and selects exam database.'],['Authentication','login.php, registration.php, edit_profile.php','Student registration/authentication; hardcoded admin login.'],['Admin','admin.php, dashboard.php, create_exam.php, add_question.php, admin_student_scores.php','Exam authoring, question drafting and score reporting.'],['Exam delivery','upcoming_exam.php, enter_exam_passkey.php, exam_instraction.php, start_exam.php, startexam.php, submitexam.php','Eligibility, passkey validation, timed UI and server-side scoring.'],['Student history','user.php, pastexam.php, f_pdf.php','Dashboard, results and PDF export.'],['Database utility','fix_db_schema.php','Inspects questions and conditionally adds section_id foreign key.'],['Tests','run-tests.ps1, tests/','Runner exists but expected tests\\run-tests.php was not found.']]]]],
['Business workflows',[
['h2','Admin: create and publish an assessment'],['table',['Step','Page / component','Outcome'],[['1','login.php','Admin authenticates against hardcoded email/password.'],['2','create_exam.php','Creates exam and sections; validates a CSRF token.'],['3','add_question.php','Selects users by skill; drafts MCQ questions; generates passkeys in browser.'],['4','save_questions.php (missing)','Expected to persist questions and assigned passkeys; current blocker.'],['5','admin_student_scores.php','Displays submitted scores and percentage.']]],
['h2','Student: take an assessment'],['table',['Step','Page / component','Outcome'],[['1','registration.php / login.php','Student creates account and signs in; password_verify() checks stored hash.'],['2','user.php → upcoming_exam.php','Eligible exams for today/tomorrow; grace window governs start availability.'],['3','enter_exam_passkey.php','One-time passkey is checked for student/exam and marked used.'],['4','exam_instraction.php / start_exam.php','Instructions or timed MCQ UI is displayed.'],['5','submitexam.php','Answers are checked, stored and score JSON is returned.'],['6','pastexam.php / f_pdf.php','Student reviews result and can generate PDF.']]]]],
['Data model and retention',[
['text','The physical schema is not checked into source control. The model below is reconstructed from application queries and should become versioned SQL migrations before the next release.'],
['table',['Table','Purpose','Key fields observed'],[['registration','Student profile and credentials','registration_id, fullname, email, skills, password and profile fields'],['exam','Assessment definition','exam_id, title, description, date/time, duration, grace window, skillRequired'],['sections','Exam sections and quotas','section_id, exam_id, section_name, noofquestions'],['questions','MCQ bank per exam/section','question_id, exam_id, section_id, question, option1–option4, correctanswer'],['passkey','Per-student access','passkey_id, registration_id, exam_id, passkey_n, is_used'],['user_answers','Submitted response detail','registration_id, exam_id, question_id, selected_answer, correct_answer, is_correct'],['scores','Aggregate result','registration_id, exam_id, score, total_questions, submitted_at']]],
['call','INTEGRITY RECOMMENDATION','Define primary keys, unique keys (email; score per student/exam; passkey assignment) and foreign keys for every relationship. Back up MySQL before running fix_db_schema.php.']]],
['Setup, runbook and verification',[
['h2','Local setup (XAMPP)'],['table',['Action','Expected result'],[['1. Place project','Keep the code at C:\\xampp\\htdocs\\exam.'],['2. Start services','Start Apache and MySQL from the XAMPP Control Panel.'],['3. Provision database','Create database exam and restore/create tables matching this document.'],['4. Configure connection','Review config.php. Current development values are localhost / root / blank password / exam.'],['5. Browse application','Open http://localhost/exam/login.php.'],['6. Smoke test','Register a student, create/publish exam, attempt it, verify score, history and PDF.']]],
['h2','Operational checks'],['bullet','Before an exam: verify grace window, section question counts, passkeys and candidate eligibility; test one candidate journey end-to-end.'],['bullet','During an exam: monitor Apache/PHP error logs and MySQL availability; do not change questions or timing without a recorded decision.'],['bullet','After an exam: export results, back up database, retain answers/scores according to policy.'],
['h2','Testing status'],['text','run-tests.ps1 attempts to run tests\\run-tests.php with XAMPP PHP or PHP on PATH. That expected test file was absent during review, so automated coverage is not currently runnable. Establish a smoke checklist, then add tests for authentication, windows, passkeys and scoring.']]],
['Security and support risks',[
['table',['Priority','Finding','Required action'],[['P0','Missing save_questions.php','Restore and test authenticated, validated endpoint.'],['P0','Hardcoded admin credential in login.php','Move to database-backed roles; rotate credential immediately.'],['P0','Admin guards incomplete/commented','Centralize role checks; protect every administration route.'],['P1','Interpolated SQL in login.php and ID queries','Use prepared statements everywhere.'],['P1','Root/blank MySQL credentials in config.php','Use least-privilege DB account and environment configuration.'],['P1','Short client-generated passkeys','Generate securely server-side and rate-limit verification.'],['P1','No versioned schema/migrations','Add migrations, backup and restore procedure.'],['P2','Duplicate/legacy exam paths','Choose canonical path; retire test and obsolete pages.'],['P2','Debug log/schema utility in web root','Remove public exposure; restrict developer tools.']]]]],
['Recommended stabilization roadmap',[
['table',['Horizon','Deliverables','Exit criteria'],[['0–2 days','Restore save endpoint; protect admin pages; rotate credential; block public developer tools.','Full create → assign → attempt → score flow works with authorization.'],['Week 1','Schema SQL/migrations, backup/restore, environment config, logging and smoke checklist.','Clean environment can be rebuilt by a new engineer.'],['Weeks 2–3','Refactor shared bootstrap/auth/database helpers; parameterize queries; centralize CSRF.','Critical routes use consistent security controls.'],['Month 1','Automated tests, passkey hardening, audit trail, roles and deployment playbook.','Release is repeatable and supportable.']]],
['h2','Ownership handover checklist'],['bullet','Obtain a current MySQL export and validate restore into a non-production instance.'],['bullet','Confirm XAMPP/PHP/MySQL versions and production-specific settings.'],['bullet','Restore or implement save_questions.php; test passkey assignment and persistence.'],['bullet','Replace hardcoded admin account; add centralized authorization.'],['bullet','Inventory and remove public exposure for test pages, fix_db_schema.php and debug.log.'],['bullet','Publish release checklist, backups, retention policy and incident contact path.']]],
['Appendix: source review notes',[
['bullet','Branding varies between SmartExam Pro and ExamPortal. Standardize it during UI maintenance.'],['bullet','start_exam.php and startexam.php offer different experiences; start_exam.php uses configured duration while startexam.php includes a fixed one-hour timer.'],['bullet','submitexam.php clears prior answer details but preserves the first score row; define a resubmission/regrading policy.'],['bullet','upcoming_exam.php only shows today/tomorrow and uses Asia/Kolkata timezone. Confirm this policy with exam operations.'],['bullet','context.md is helpful background but contains discrepancies with source, including treating the missing save_questions.php as present.']]]
];
foreach($sections as [$title,$items]){ $body .= p($title,'Heading1',true,'10233F',34); foreach($items as $it){ if($it[0]==='text')$body.=p($it[1],'Normal',false,'202630',21); elseif($it[0]==='h2')$body.=p($it[1],'Heading2',true,'1C6E78',25); elseif($it[0]==='bullet')$body.=bullet($it[1]); elseif($it[0]==='table')$body.=tbl($it[1],$it[2]); elseif($it[0]==='call')$body.='<w:tbl><w:tblPr><w:tblW w:w="9360" w:type="dxa"/><w:shd w:fill="FFF8EC"/><w:tblBorders><w:top w:val="single" w:sz="10" w:color="C89B3C"/><w:left w:val="single" w:sz="10" w:color="C89B3C"/><w:bottom w:val="single" w:sz="10" w:color="C89B3C"/><w:right w:val="single" w:sz="10" w:color="C89B3C"/></w:tblBorders></w:tblPr><w:tr><w:tc><w:p>'.r($it[1].'  ',true,'C89B3C',20).r($it[2],false,'202630',20).'</w:p></w:tc></w:tr></w:tbl><w:p/>'; }}
$body .= '<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1000" w:right="1150" w:bottom="950" w:left="1150" w:header="500" w:footer="500" w:gutter="0"/><w:headerReference w:type="default" r:id="rId1"/><w:footerReference w:type="default" r:id="rId2"/></w:sectPr>';
$document='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>'.$body.'</w:body></w:document>';
$styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:sz w:val="21"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:qFormat/></w:style><w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:outlineLvl w:val="0"/></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:outlineLvl w:val="1"/></w:style><w:style w:type="paragraph" w:styleId="Kicker"><w:name w:val="Kicker"/></w:style><w:style w:type="paragraph" w:styleId="ListBullet"><w:name w:val="List Bullet"/><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr></w:style></w:styles>';
$numbering='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" w:pos="720"/></w:tabs><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num></w:numbering>';
$header='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="10" w:space="4" w:color="C89B3C"/></w:pBdr></w:pPr>'.r('SMARTEXAM PRO  /  TECHNICAL HANDOVER',true,'65758B',16).'</w:p></w:hdr>';
$footer='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:p><w:pPr><w:jc w:val="right"/></w:pPr>'.r('Confidential internal handover  |  SmartExam Pro',false,'65758B',16).'</w:p></w:ftr>';
$types='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>';
$rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';
$docrels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/></Relationships>';
$zip=new ZipArchive(); if($zip->open($out,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true) die('Cannot create document'); $zip->addFromString('[Content_Types].xml',$types); $zip->addFromString('_rels/.rels',$rels); $zip->addFromString('word/document.xml',$document); $zip->addFromString('word/styles.xml',$styles); $zip->addFromString('word/numbering.xml',$numbering); $zip->addFromString('word/header1.xml',$header); $zip->addFromString('word/footer1.xml',$footer); $zip->addFromString('word/_rels/document.xml.rels',$docrels); $zip->close(); echo basename($out).PHP_EOL;
